# Generated by Django 4.2.4 on 2023-08-19 19:17

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('tom', models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='Vol', max_length=250)),
                ('slug', models.SlugField(null=True)),
                ('original_file', models.FileField(upload_to='encyclopedia/toms')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('tom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encyclopedia.volume')),
            ],
        ),
    ]
