# Generated by Django 4.2.4 on 2023-08-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_last',
            field=models.BooleanField(default=False),
        ),
    ]
