# Generated by Django 4.2.4 on 2023-08-19 19:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulation',
            name='sparings',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='belt',
            name='kupslug',
            field=models.SlugField(primary_key=True, serialize=False, unique=True),
        ),
    ]
