# Generated by Django 4.2.4 on 2023-08-19 19:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0002_regulation_sparings_alter_belt_kupslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulation',
            name='theory',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
